stop-words = "data/lemur-stopwords.txt"
prefix = "data/"

dataset = "news"
corpus = "tutorial.toml"
index = "news-idx"

query-judgements = "data/news/cranfield-qrels.txt"

[[analyzers]]
method = "ngram-word"
ngram = 1
filter = "default-unigram-chain"
